import type { SiteContent } from "@/lib/site-content-schema";

export const defaultContent: SiteContent = {
  brand: {
    name: "FORM / FRAME",
    descriptor: "Independent motion & film studio",
    email: "hello@formframe.studio",
    phone: "+1 (415) 555-0142",
    location: "San Francisco · Working everywhere",
    seoTitle: "FORM / FRAME — Motion for what matters",
    seoDescription: "An independent motion and film studio building visual worlds with feeling, precision, and a little bit of the unexpected.",
    instagramUrl: "https://www.instagram.com/",
  },
  hero: {
    eyebrow: "Independent motion studio · Est. 2018",
    title: "Make the impossible",
    highlight: "feel inevitable.",
    body: "We turn ambitious stories into moving images, visual worlds, and sound that stay with you long after the screen goes dark.",
    cta: "Start a conversation",
    secondaryCta: "Explore our work",
    projectCount: "32",
  },
  about: {
    eyebrow: "A studio for the in-between",
    title: "Where precision meets the unexpected.",
    intro: "We like the moment before a good idea becomes a thing you can hold. That is usually where we are found.",
    body: "FORM / FRAME is an independent creative studio working across motion design, film, and digital worlds. We bring strategists, directors, artists, and technologists to one table, then make something none of us could make alone.",
    closing: "We stay small on purpose. The best work is made by people close enough to care about every detail—and curious enough to keep looking for a better one.",
    statement: "Good motion catches the eye. Great motion changes what the eye remembers.",
    ctaTitle: "We are better\nwhen we make it together.",
    ctaButton: "Start with a hello",
    years: "08",
    collaborators: "24",
    timeZones: "06",
    milestones: [
      { year: "2018", title: "The first frame", description: "An independent studio takes shape around one shared belief: the feeling is part of the craft." },
      { year: "2021", title: "A wider lens", description: "A small circle grows into a flexible community of makers across film, motion, and sound." },
      { year: "2026", title: "Still curious", description: "We keep the team close, the questions open, and every new project a chance to see differently." },
    ],
  },
  services: [
    {
      id: "motion-systems",
      number: "01",
      title: "Motion systems",
      description: "A living visual language for brands ready to move differently.",
      detail: "From the first kinetic sketch to a fully documented motion toolkit, we create systems that make every brand moment feel unmistakably connected.",
      tags: ["Brand motion", "Identity systems", "Campaign toolkits"],
    },
    {
      id: "film-campaigns",
      number: "02",
      title: "Film & campaigns",
      description: "Short-form stories with the weight of a feature.",
      detail: "We take a film from its first beat through production and finishing, shaping performances, picture, and sound into a story with staying power.",
      tags: ["Creative direction", "Production", "Editorial"],
    },
    {
      id: "world-building",
      number: "03",
      title: "3D worlds",
      description: "Impossible spaces made tactile, luminous, and real.",
      detail: "CG environments, product films, and visual experiments built from the physics up, with room for a little beautiful impossibility.",
      tags: ["CGI", "Art direction", "Look development"],
    },
    {
      id: "sound-design",
      number: "04",
      title: "Sound & finishing",
      description: "The last layer that makes a whole world click into place.",
      detail: "A considered final pass on picture, grade, and sound. Every cut has intention; every quiet moment earns its place.",
      tags: ["Sound design", "Color grade", "Mastering"],
    },
  ],
  projects: [
    {
      slug: "afterlight",
      title: "Afterlight",
      category: "Campaign film · 3D",
      year: "2025",
      summary: "A fragrance film about the last light of a day that never quite ends.",
      description: "For independent fragrance house Nacre, our team built a sunlit glass world from nothing but light, atmosphere, and movement. Every shot follows the last warm reflection as it slips over the horizon.",
      client: "Nacre House",
      role: "Creative direction, CGI, edit, sound",
      cover: "/images/project-afterlight.svg",
      accent: "#d8ad78",
      deliverables: ["Hero film", "Social cutdowns", "Product loops", "Sound identity"],
    },
    {
      slug: "signal-noise",
      title: "Signal / Noise",
      category: "Visual identity · Motion",
      year: "2025",
      summary: "A kinetic identity for a culture that refuses to sit still.",
      description: "A pulse-led visual system for the fictional independent music label NØR. We translated the beautiful friction between analog machines and digital sound into a flexible identity, live visuals, and a modular campaign toolkit.",
      client: "NØR Records",
      role: "Identity, motion system, launch visuals",
      cover: "/images/project-signal-noir.svg",
      accent: "#9a7cff",
      deliverables: ["Motion identity", "Artist loops", "Stage visuals", "Campaign toolkit"],
    },
    {
      slug: "soft-geometry",
      title: "Soft Geometry",
      category: "Art direction · Film",
      year: "2024",
      summary: "A study in objects, tactility, and the things that connect us.",
      description: "An original short-form film made as an exploration of everyday rituals. Sculptural shapes, soft camera movement, and a quiet score build a visual essay about attention.",
      client: "FORM / FRAME Originals",
      role: "Film, art direction, edit, sound",
      cover: "/images/project-soft-geometry.svg",
      accent: "#d4eb89",
      deliverables: ["Original film", "Director's cut", "Exhibition loop"],
    },
  ],
  process: [
    { id: "listen", title: "Listen closely", description: "We start with the thing you need the audience to feel—not the deliverable list." },
    { id: "shape", title: "Shape the idea", description: "A clear point of view gives every frame and every choice somewhere to go." },
    { id: "make", title: "Make it move", description: "Small senior teams build, test, and refine the work in the open with you." },
    { id: "deliver", title: "Leave a feeling", description: "Every master is considered in context, then handed over ready for its next life." },
  ],
};
